set(MITK_MODULES
  DiffusionImage
  DiffusionPreprocessing
  DiffusionModelling
  DiffusionRegistration
  FiberBundle
  FiberProcessing
  FiberTracking
  MriSimulation
  FiberDissection
  IVIM
  DiffusionCmdApps
)
