set(Plugin-Name "MITK Partial Volume Analysis")
set(Plugin-Version "1.0.0")
set(Plugin-Vendor "DKFZ, Medical Image Computing")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.controls org.mitk.gui.qt.common)
