set(MITK_PLUGINS
  org.mitk.gui.qt.diffusionimaging.controls:OFF
  org.mitk.gui.qt.diffusionimaging.denoising:OFF
  org.mitk.gui.qt.diffusionimaging.fiberfox:OFF
  org.mitk.gui.qt.diffusionimaging.fiberprocessing:OFF
  org.mitk.gui.qt.diffusionimaging.ivim:OFF
  org.mitk.gui.qt.diffusionimaging.odfpeaks:OFF
  org.mitk.gui.qt.diffusionimaging.partialvolume:OFF
  org.mitk.gui.qt.diffusionimaging.preprocessing:OFF
  org.mitk.gui.qt.diffusionimaging.reconstruction:OFF
  org.mitk.gui.qt.diffusionimaging.registration:OFF
  org.mitk.gui.qt.diffusionimaging.tractography:OFF
  org.mitk.gui.qt.diffusionimagingapp:OFF
)
