set(Plugin-Name "MITK Diffusion")
set(Plugin-Version "1.0")
set(Plugin-Vendor "DKFZ, Medical Image Computing")
set(Plugin-ContactAddress "http://www.mitk.org")
set(Require-Plugin org.mitk.gui.qt.ext)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.controls)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.denoising)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.fiberfox)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.fiberprocessing)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.ivim)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.odfpeaks)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.partialvolume)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.preprocessing)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.python)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.reconstruction)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.registration)
set(Require-Plugin org.mitk.gui.qt.diffusionimaging.tractography)
set(Plugin-Activator QmitkDiffusionImagingAppApplicationPlugin)


